### PR TITLE
Adding master_board/SPIMotor support

### PR DESCRIPTION
**Pull request by jviereck**
This implements `class SPIMotor: MotorInterface` for talking to motors controlled via a master_board and the udrivers connected via SPI (that's why the name SPIMotor).

### CODE REVIEW

**Comment by mwuethri** [comment]
why is it necessary to add an SPIMotor? the idea is that the motor takes as input a pointer to the MotorBoardInterface, and is hence agnostic to whether the it is a CanMotorBoard or SPIMotorBoard. Is there a reason why this does not work?

**Comment by mwuethri** [comment]
minor comment: if you do formatting changes, please put them in a separate commit, it makes reviewing much easier.

**Comment by jviereck** [comment]
Okay, will do in the future (Max was fine with this).

**Comment by MaximilienNaveau** [comment]
> why is it necessary to add an SPIMotor? the idea is that the motor takes as input a pointer to the MotorBoardInterface, and is hence agnostic to whether the it is a CanMotorBoard or SPIMotorBoard. Is there a reason why this does not work?

This problem comes form the fact that from the CAN api each udrivers where independent. So the send_if_new was per motor/udriver.
With Thomas api basically all information transit at every tick. So the send if changed does not make any sens anymore.
And we cannot use the send per motor but we need to have a global "robot" send.

> another reason for doing it this way is that then blmc_drivers does not need to depend on the SPI stuff.

I really do not follow you on this comment because even if include an SPIMotorBoard we would end-up depending on the master-board API...

**Comment by MaximilienNaveau** [comment]
We should close this PR in favor of: https://github.com/open-dynamic-robot-initiative/blmc_drivers/pull/4 as the new one maintain the compatibility with the blmc_drivers software architecture.

**Pull request closed without merging**
